# Generated by Django 5.0.6 on 2024-06-07 23:11

import datetime
import django.db.models.deletion
import django_enumfield.db.fields
import flightSearch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50, unique=True, verbose_name='Country name')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='City name')),
                ('iataCode', models.CharField(max_length=3, unique=True, verbose_name='Airport code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightSearch.country', verbose_name='Country name')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField(default=datetime.date(2024, 6, 8), verbose_name='Departure date')),
                ('cabin', django_enumfield.db.fields.EnumField(default=1, enum=flightSearch.models.Cabin)),
                ('flightNumber', models.CharField(max_length=20, unique=True, verbose_name='Flight number')),
                ('arrivalAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivalAirport', to='flightSearch.airport', verbose_name='Arrival airport')),
                ('departureAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departureAirport', to='flightSearch.airport', verbose_name='Departure airport')),
            ],
        ),
    ]
