# Generated by Django 5.0.6 on 2024-06-09 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureDate',
            field=models.DateField(default=datetime.date(2024, 6, 9), verbose_name='Departure date'),
        ),
    ]
