# Generated by Django 5.0.6 on 2024-06-09 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flightSearch', '0002_alter_flight_departuredate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inbound', to='flightSearch.flight')),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outbound', to='flightSearch.flight')),
            ],
        ),
    ]
