# Generated by Django 5.0.6 on 2024-06-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightReservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tripType',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
