# Generated by Django 5.0.6 on 2024-06-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightReservations', '0002_reservation_triptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='inbound',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='outbound',
            field=models.CharField(max_length=10),
        ),
    ]
