# Generated by Django 5.0.6 on 2024-06-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightReservations', '0003_alter_reservation_inbound_alter_reservation_outbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='inbound',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
